Repository micronaut-projects/micronaut-email, pull requests merged in 2022-02, with the labels that each got.

#26 doc: the artifact id is micronaut-amazon-ses
  src/main/docs/guide/integrations/ses.adoc
Labels: type: docs

#21 build: bump up to Micronaut 3.3.0
  gradle.properties
Labels: relates-to: build

#28 build: bump up sendgrid to 4.8.3
  gradle.properties
Labels: type: dependency-upgrade
