Repository micronaut-projects/micronaut-email, pull requests merged in 2022-03, with the labels that each got.

#39 build: update build plugin to 5.2.3
  settings.gradle
Labels: relates-to: build

#33 build: quality-reporting gradle plugin
  README.md
  build.gradle
Labels: relates-to: build

#40 build: update to gradle 7.4.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#43 ci: github actions update
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#45 bug: wrap html and text bodies in an 'alternative' multipart
  email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java
  email-javamail/build.gradle
  email-javamail/src/main/java/io/micronaut/email/javamail/sender/JavaxEmailSender.java
  email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy
Labels: bug

#42 build: sendgrid from 4.8.3 to 4.9.0
  gradle.properties
Labels: type: dependency-upgrade
