Repository micronaut-projects/micronaut-email, pull requests merged in 2022-06, with the labels that each got.

#95 Add documentation for Consumer based config
  src/main/docs/guide/customization.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/email/docs/CustomizedJavaMailService.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/email/docs/CustomizedJavaMailServiceSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/email/docs/MockEmailSender.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/email/docs/CustomizedJavaMailService.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/email/docs/CustomizedJavaMailServiceTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/email/docs/MockEmailSender.kt
  test-suite/src/test/java/io/micronaut/email/docs/CustomizedJavaMailService.java
  test-suite/src/test/java/io/micronaut/email/docs/CustomizedJavaMailServiceTest.java
  test-suite/src/test/java/io/micronaut/email/docs/MockEmailSender.java
Labels: documentation

#88 ci: github action sync
  .editorconfig
  .gitattributes
  .github/workflows/graalvm.yml
  gradlew.bat
Labels: relates-to: build

#94 JavaMail authentication by configuration
  email-javamail/src/main/java/io/micronaut/email/javamail/sender/DefaultSessionProvider.java
  email-javamail/src/main/java/io/micronaut/email/javamail/sender/authentication/AuthenticatorFactory.java
  email-javamail/src/main/java/io/micronaut/email/javamail/sender/authentication/JavaMailAuthenticationConfiguration.java
  email-javamail/src/main/java/io/micronaut/email/javamail/sender/authentication/JavaMailAuthenticationConfigurationProperties.java
  email-javamail/src/main/java/io/micronaut/email/javamail/sender/authentication/package-info.java
  email-javamail/src/test/groovy/io/micronaut/email/javamail/AuthenticationPropertiesProviderViaConfigurationSpec.groovy
  email-javamail/src/test/groovy/io/micronaut/email/javamail/AuthenticationViaConfigurationSpec.groovy
  src/main/docs/guide/integrations/javamail.adoc
Labels: enhancement

#97 Keep MIME resources for sending email in a native app
  email-javamail-composer/src/main/resources/META-INF/native-image/io.micronaut.email/email-javamail-composer/reflect-config.json
  email-javamail-composer/src/main/resources/META-INF/native-image/io.micronaut.email/email-javamail-composer/resource-config.json
Labels: type: bug

#98 Merge 1.2.x
  email-javamail-composer/src/main/resources/META-INF/native-image/io.micronaut.email/email-javamail-composer/reflect-config.json
  email-javamail-composer/src/main/resources/META-INF/native-image/io.micronaut.email/email-javamail-composer/resource-config.json
  gradle.properties
Labels: relates-to: build
