Repository micronaut-projects/micronaut-email, pull requests merged in 2023-07, with the labels that each got.

#243 [email] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#251 [email] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#256 Email to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#263 AnyRecipient should work for Micronaut Validation and Micronaut Hibernate Validator
  email-javamail-composer/build.gradle.kts
  email-javamail/build.gradle.kts
  email-mailjet/build.gradle.kts
  email-postmark/build.gradle.kts
  email-sendgrid/build.gradle.kts
  email-template/build.gradle.kts
  email/build.gradle.kts
  email/src/main/java/io/micronaut/email/validation/AnyRecipient.java
  email/src/main/java/io/micronaut/email/validation/AnyRecipientConstraintValidationFactory.java
  email/src/main/java/io/micronaut/email/validation/AnyRecipientValidator.java
  email/src/test/groovy/io/micronaut/email/EmailSpec.groovy
  email/src/test/groovy/io/micronaut/email/validation/AnyRecipientsValidatorSpec.groovy
  gradle/libs.versions.toml
  settings.gradle
  test-suite-hibernate-validator/build.gradle.kts
  test-suite-hibernate-validator/src/test/java/io/micronaut/email/tests/hibernatevalidator/EmailValidationTest.java
  test-suite-hibernate-validator/src/test/resources/logback.xml
Labels: bug

#270 [email] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#271 Populate Postmark fields: cc/bcc/replyTo
  email-postmark/src/main/java/io/micronaut/email/postmark/PostmarkEmailComposer.java
  email-postmark/src/test/groovy/io/micronaut/email/postmark/PostmarkEmailComposerSpec.groovy
Labels: type: improvement

#265 Allow more than one Reply-To contact in order to be compliant with the Mail RFC
  email-amazon-ses/src/main/java/io/micronaut/email/ses/SesEmailComposer.java
  email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
  email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java
  email-javamail-composer/src/test/groovy/io/micronaut/email/javamail/composer/DefaultMessageComposerSpec.groovy
  email-mailjet/build.gradle.kts
  email-mailjet/src/main/java/io/micronaut/email/mailjet/MailjetEmailComposer.java
  email-mailjet/src/test/groovy/io/micronaut/email/mailjet/MailjetEmailComposerSpec.groovy
  email-postmark/src/main/java/io/micronaut/email/postmark/PostmarkEmailComposer.java
  email-postmark/src/test/groovy/io/micronaut/email/postmark/PostmarkEmailComposerSpec.groovy
  email-sendgrid/build.gradle.kts
  email-sendgrid/src/main/java/io/micronaut/email/sendgrid/SendgridEmailComposer.java
  email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
  email/src/main/java/io/micronaut/email/Email.java
  email/src/test/groovy/io/micronaut/email/EmailSpec.groovy
Labels: type: improvement

#272 Introduce `Attachment.disposition`
  email-amazon-ses/build.gradle.kts
  email-amazon-ses/src/test/groovy/io/micronaut/email/ses/SesEmailComposerSpec.groovy
  email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java
  email-javamail-composer/src/test/groovy/io/micronaut/email/javamail/composer/DefaultMessageComposerSpec.groovy
  email-mailjet/src/main/java/io/micronaut/email/mailjet/MailjetEmailComposer.java
  email-mailjet/src/test/groovy/io/micronaut/email/mailjet/MailjetEmailComposerSpec.groovy
  email-postmark/src/main/java/io/micronaut/email/postmark/PostmarkEmailComposer.java
  email-postmark/src/test/groovy/io/micronaut/email/postmark/PostmarkEmailComposerSpec.groovy
  email-sendgrid/src/main/java/io/micronaut/email/sendgrid/SendgridEmailComposer.java
  email-sendgrid/src/test/groovy/io/micronaut/email/sendgrid/SendgridEmailComposerSpec.groovy
  email/src/main/java/io/micronaut/email/Attachment.java
Labels: type: improvement
