Repository micronaut-projects/micronaut-email, pull requests merged in 2023-06, with the labels that each got.

#228 [email] Update common files for branch master
  .github/renovate.json
Labels: relates-to: build

#216 email to M6
  build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.email-base.gradle
  email-javamail/build.gradle.kts
  email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy
  email-template/src/main/java/io/micronaut/email/template/DefaultTemplateBodyDecorator.java
  email-template/src/main/java/io/micronaut/email/template/TemplateBodyDecorator.java
  email/src/main/java/io/micronaut/email/Email.java
  email/src/test/groovy/io/micronaut/email/TransactionalEmailSenderSpec.groovy
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
Labels: type: dependency-upgrade

#232 [email] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#233 Upgrade Jakarta Mail to latest spec and implementation.
  email-javamail-composer/build.gradle.kts
  email-javamail-composer/src/main/resources/META-INF/native-image/io.micronaut.email/email-javamail-composer/reflect-config.json
  email-javamail/build.gradle.kts
  gradle/libs.versions.toml
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/integrations/javamail.adoc
Labels: type: breaking

#242 Email to RC1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
